@Host = https://localhost:44377

GET {{Host}}/api/convert/?url=https://dndjp.sakura.ne.jp/OUTPUT.php?ID=46016
Accept: application/json

###

GET {{Host}}/api/convert/?url=https://dndjp.sakura.ne.jp/OUTPUT_BROKEN.php?ID=46016
Accept: application/json

###

GET {{Host}}/api/convert/?url=https://dndjp.sakura.ne.jp/OUTPUT.php?ID=45939
Accept: application/json

