name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  buildImage:
    name: Build Docker image and publish to Azure Container Registry
    environment: Production
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      imageUri: ${{ steps.buildImage.outputs.imageUri }}
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Log in to Azure Container Registry
      run: |
        ACCESS_TOKEN=$(az acr login --name ${{ vars.AZURE_CONTAINER_REGISTRY }} --output json --expose-token | jq -r '.accessToken')
        docker login "${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io" -u 00000000-0000-0000-0000-000000000000 -p $ACCESS_TOKEN

    - name: Build and push image to ACR
      id: buildImage
      run: |
        IMAGE_TAG=latest
        IMAGE_NAME="${{ vars.AZURE_CONTAINER_REPOSITORY_NAME }}:$IMAGE_TAG"
        IMAGE_URI=${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/$IMAGE_NAME

        docker build \
          --build-arg COMMIT_HASH=${{ github.sha }} \
          -t $IMAGE_URI \
          -f "src/CatsUdon.CharacterSheets.Web/Dockerfile" \
          .

        docker push $IMAGE_URI

        echo "imageUri=$IMAGE_URI" >> $GITHUB_OUTPUT